# Generated by Django 5.2.17 on 2026-09-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question text', max_length=500)),
                ('answer', models.TextField(help_text='Detailed answer text')),
                ('category', models.CharField(default='General', help_text='e.g. General, Pricing, Security', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('is_active', models.BooleanField(default=True, help_text='Visible on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='code', help_text='Icon identifier', max_length=100)),
                ('price', models.CharField(blank=True, default='', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('initials', models.CharField(blank=True, help_text='e.g. HP, SP', max_length=10)),
                ('role', models.CharField(help_text='e.g. Founder, Full-Stack Developer', max_length=200)),
                ('bio', models.TextField()),
                ('photo_url', models.URLField(blank=True, help_text='Optional profile photo URL', max_length=500, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
